export enum AppRoutes {
    HOME = '',
    CATALOG = 'catalog',
    FAVOURITE = 'favorites',
    ADMIN = 'admin',
    PRODUCTS = 'products',
    PRODUCT_DETAIL = 'products/:id',
    PAGE_NOT_FOUND = '**',
    CART = 'cart',
    CHECKOUT = 'checkout',
    SHIPPING = 'shipping',
    DELIVERY = 'delivery',
    PAYMENT = 'payment',
    REVIEW = 'review',
    CONFIRMATION = 'order-confirmation',
    CHECKOUT_SHIPPING = 'checkout/shipping',
    CHECKOUT_DELIVERY = 'checkout/delivery',
    CHECKOUT_PAYMENT = 'checkout/payment',
    CHECKOUT_REVIEW = 'checkout/review',
}